version: '3.1'

services:
  registry:
    image: registry:2.7.1
    container_name: registry
    ports:
      - "5000:5000"
  act-ubuntu:
    container_name: ubuntu-builder
    platform: linux/amd64
    build: act-ubuntu-dep/.
    tty: true
    restart: on-failure
    depends_on:
      - registry

  localstack:
    image: localstack/localstack:latest
    environment:
      - EDGE_PORT=4566
      - SERVICES=serverless,sqs
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - '4566-4583:4566-4583'
    volumes:
      - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
