service: sls1

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, 'local'}
  deploymentBucket:
    name: serverless.${self:provider.region}.deploys
    maxPreviousDeploymentArtifacts: 10
    serverSideEncryption: AES256

plugins:
  - serverless-localstack
  - serverless-deployment-bucket
  - serverless-iam-roles-per-function
custom:
  localstack:
    stages:
      - local
    host: http://${env:LOCALSTACK_HOST, 'localhost'}
    edgePort: 4566
    endpoints:
      S3: http://localhost:4572
      DynamoDB: http://localhost:4569
      CloudFormation: http://localhost:4581
      SNS: http://localhost:4575
      SQS: http://localhost:4576
      Lambda: http://localhost:4574
      Kinesis: http://localhost:4568
    lambda:
      # Enable this flag to improve performance
      mountCode: true

functions:
  greet:
    handler: greeter/handler.greet
