service: serverless-localstack

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  lambdaHashingVersion: 20201221

plugins:
  - serverless-localstack

custom:
  Resources:
    S3BucketData:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-data
  localstack:
    stages:
      - dev
    host: http://localhost
    endpointFile: localstack_endpoints.json
    lambda:
      # Enable this flag to improve performance
      mountCode: True

functions:
  greet:
    handler: greet.handler
