name: Deploy
on:
  push:
    branches:
      - master
jobs:
  localstack:
    name: LocalStack Deployment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
        DEPLOY_STAGE: ['dev']
    steps:
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - uses: actions/checkout@v2
      - name: Install Python dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install -r requirements.txt
      - name: Install LocalStack
        run: |
          pip3 install localstack
          docker pull localstack/localstack
          localstack start -d
          echo "Waiting for LocalStack to startup..."
          localstack wait -t 30
          echo "Startup complete"
        continue-on-error: true
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Serverless
        run: npm install -g serverless@2.18.0-6c67cd7f
      - name: Deploy AWS Resources via Serverless
        env:
          DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SLS_DEBUG: 1
        run: |
          serverless plugin install --name serverless-localstack
          serverless deploy --stage=${{ matrix.DEPLOY_STAGE }} --verbose
      # Execute Tests lambda
      - name: Run test for sample lambda
        run: |
          cd lambda
          pytest -sv
